server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
        # 上面表示 如果要访问http://localhost:8001/get/payment/** 需要
        # http://localhost:9527/get/payment/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/get/lb/**   #断言,路径相匹配的进行路由

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka