server:
  port: 8001


spring:
  application:
    name: nacos-payment-provider # 服务注册的时候在注册中心的名字，多个服务使用同一个应用名，认定为同一个服务，这个时候进行服务转发的时候才会进行调用
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1000  #配置的Nacos地址（本机的写localhost:8848，服务器的写IP地址）
    sentinel:
      transport:
        #配置Sentin dashboard地址（改成自己的服务器ip地址，本地用localhost‍）
        dashboard: localhost:8858
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
  datasource: # 数据库连接池信息，如果需要使用数据库必须要用这个
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.23.228.88:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis: # 如果使用mybatis需要使用这个
  mapperLocations: classpath:mapper/*.xml # mapper对应的sql的扫描路径
  type-aliases-package: com.li.entities


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true # 开启feign服务